version: '3.8'
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    ports:
      - "8080:80"
    volumes:
      - filestorage:/srv
      - filebrowser-config:/config
    environment:
      - PUID=1001
      - PGID=1001
    restart: unless-stopped
    command: --noauth

volumes:
  filestorage:
    external: true
  filebrowser-config: